export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'subject-max-length': [2, 'always', 100],
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 120],
    'footer-max-line-length': [2, 'always', 120],
    'footer-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 100],
    'scope-enum': [
      2,
      'always',
      [
        'cli',
        'agent',
        'agent-runtime',
        'workflow',
        'workflow-executor',
        'template',
        'provider',
        'nl',
        'chat',
        'repl',
        'docs',
        'ci',
        'deps',
        'core',
        'extension',
        'logger',
        'release',
        'config',
        'vscode-extension',
        'doc-task-contract',
      ],
    ],
    'scope-case': [2, 'always', 'lower-case'],
  },
  helpUrl: 'https://github.com/tongxin779977/VectaHub/blob/main/CONTRIBUTING.md',
  ignores: [(message) => message.startsWith('Merge ') || message.startsWith('Revert ') || /^chore: release v\d/.test(message)],
};