import type { KnownTool } from './types.js';

export const KNOWN_TOOLS: KnownTool[] = [
  {
    id: 'git',
    name: 'git',
    version: '>=2.0.0',
    versionRequirement: '>=2.0.0',
    description: '分布式版本控制系统',
    checkCommand: 'git --version',
    checkOutputRegex: 'git version ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['git --version'],
    categories: ['vcs'],
    confidence: 0.95,
  },
  {
    id: 'npm',
    name: 'npm',
    version: '>=6.0.0',
    versionRequirement: '>=6.0.0',
    description: 'Node.js 包管理器',
    checkCommand: 'npm --version',
    checkOutputRegex: '([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'npm',
    versionCommands: ['npm --version'],
    categories: ['package-manager'],
    confidence: 0.95,
  },
  {
    id: 'docker',
    name: 'docker',
    version: '>=19.0.0',
    versionRequirement: '>=19.0.0',
    description: '容器化平台',
    checkCommand: 'docker --version',
    checkOutputRegex: 'Docker version ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['docker --version'],
    categories: ['container'],
    confidence: 0.90,
  },
  {
    id: 'node',
    name: 'node',
    version: '>=18.0.0',
    versionRequirement: '>=18.0.0',
    description: 'Node.js 运行时',
    checkCommand: 'node --version',
    checkOutputRegex: 'v([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['node --version'],
    categories: ['runtime'],
    confidence: 0.95,
  },
  {
    id: 'python',
    name: 'python',
    version: '>=3.8.0',
    versionRequirement: '>=3.8.0',
    description: 'Python 编程语言',
    checkCommand: 'python3 --version',
    checkOutputRegex: 'Python ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['python3 --version', 'python --version'],
    categories: ['language'],
    confidence: 0.95,
  },
  {
    id: 'yarn',
    name: 'yarn',
    version: '>=1.22.0',
    versionRequirement: '>=1.22.0',
    description: 'Yarn 包管理器',
    checkCommand: 'yarn --version',
    checkOutputRegex: '([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'npm',
    versionCommands: ['yarn --version'],
    categories: ['package-manager'],
    confidence: 0.85,
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    version: '>=7.0.0',
    versionRequirement: '>=7.0.0',
    description: 'pnpm 包管理器',
    checkCommand: 'pnpm --version',
    checkOutputRegex: '([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'npm',
    versionCommands: ['pnpm --version'],
    categories: ['package-manager'],
    confidence: 0.85,
  },
  {
    id: 'typescript',
    name: 'tsc',
    version: '>=4.0.0',
    versionRequirement: '>=4.0.0',
    description: 'TypeScript 编译器',
    checkCommand: 'tsc --version',
    checkOutputRegex: 'Version ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'npm',
    versionCommands: ['tsc --version'],
    categories: ['compiler'],
    confidence: 0.85,
  },
  {
    id: 'curl',
    name: 'curl',
    version: '>=7.0.0',
    versionRequirement: '>=7.0.0',
    description: '命令行网络工具',
    checkCommand: 'curl --version',
    checkOutputRegex: 'curl ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['curl --version'],
    categories: ['network'],
    confidence: 0.95,
  },
  {
    id: 'wget',
    name: 'wget',
    version: '>=1.0.0',
    versionRequirement: '>=1.0.0',
    description: '网络下载工具',
    checkCommand: 'wget --version',
    checkOutputRegex: 'GNU Wget ([0-9]+)\\.([0-9]+)\\.([0-9]+)',
    packageManager: 'brew',
    versionCommands: ['wget --version'],
    categories: ['network'],
    confidence: 0.95,
  },
];

export function getKnownTool(name: string): KnownTool | undefined {
  return KNOWN_TOOLS.find(t => t.name === name || t.id === name);
}

export function getAllKnownTools(): KnownTool[] {
  return [...KNOWN_TOOLS];
}
